kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv0001-pvc-web-dmz
  namespace: web-dmz
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

